[project]
org-name = "wso2"
version = "0.9.52"
license= ["Apache-2.0"]
authors = ["WSO2"]
keywords = ["ballerina", "amazons3", "amazon", "client", "connector"]
repository = "https://github.com/wso2-ballerina/module-amazons3"
